// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsG1g_fzm_63BWVxMrlLR9FHP7X36k5X8',
    appId: '1:122097991719:web:495063109594fe05274e02',
    messagingSenderId: '122097991719',
    projectId: 'kisan-ai-app-4556',
    authDomain: 'kisan-ai-app-4556.firebaseapp.com',
    storageBucket: 'kisan-ai-app-4556.firebasestorage.app',
    measurementId: 'G-H8VT2DQ18E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmytZKyZOuwqMZrg1WIDeJsHJsbwAi9eA',
    appId: '1:122097991719:android:474a371ffec2bb39274e02',
    messagingSenderId: '122097991719',
    projectId: 'kisan-ai-app-4556',
    storageBucket: 'kisan-ai-app-4556.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDl4CCfwvrw5Y2oTB94oHSZ2QEbL8OoXc4',
    appId: '1:122097991719:ios:862f39823a5dd48e274e02',
    messagingSenderId: '122097991719',
    projectId: 'kisan-ai-app-4556',
    storageBucket: 'kisan-ai-app-4556.firebasestorage.app',
    iosBundleId: 'com.example.kisanAi',
  );
}
